//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlannerCalendarClient.ServiceDfdg.DfdgService {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.bm.dk/xml/schemas/2011/01/12/")]
    public partial class FaultDetails : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int errorCodeField;
        
        private bool errorCodeFieldSpecified;
        
        private string messageField;
        
        private string innerExceptionField;
        
        private string stackTraceField;
        
        private string sourceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int ErrorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
                this.RaisePropertyChanged("ErrorCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ErrorCodeSpecified {
            get {
                return this.errorCodeFieldSpecified;
            }
            set {
                this.errorCodeFieldSpecified = value;
                this.RaisePropertyChanged("ErrorCodeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("Message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string InnerException {
            get {
                return this.innerExceptionField;
            }
            set {
                this.innerExceptionField = value;
                this.RaisePropertyChanged("InnerException");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string StackTrace {
            get {
                return this.stackTraceField;
            }
            set {
                this.stackTraceField = value;
                this.RaisePropertyChanged("StackTrace");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string Source {
            get {
                return this.sourceField;
            }
            set {
                this.sourceField = value;
                this.RaisePropertyChanged("Source");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RequestUserTypeIdentifierType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(OrganisationTypeIdentifierType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CalendarEventReceiptErrorCodeType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.bm.dk/pjaktass/2013/06/07/CodeListBase/")]
    public partial class CodeListItemIdentifierType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int codeListItemIdentifierField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int CodeListItemIdentifier {
            get {
                return this.codeListItemIdentifierField;
            }
            set {
                this.codeListItemIdentifierField = value;
                this.RaisePropertyChanged("CodeListItemIdentifier");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.bm.dk/pjaktass/2015/01/21/RequestUserTypeIdentifierCodeList/")]
    public partial class RequestUserTypeIdentifierType : CodeListItemIdentifierType {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.bm.dk/pjaktass/2015/01/21/OrganisationTypeIdentifierCodeList/")]
    public partial class OrganisationTypeIdentifierType : CodeListItemIdentifierType {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.bm.dk/PlannerExternalCalendarService/2015/03/27/")]
    public partial class CalendarEventReceiptErrorCodeType : CodeListItemIdentifierType {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.bm.dk/PlannerExternalCalendarService/2015/03/27/")]
    public partial class CalendarEventReceiptType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Guid plannerResourceIdentifierField;
        
        private bool plannerResourceIdentifierFieldSpecified;
        
        private System.Guid calendarEventIdentifierField;
        
        private System.DateTime eventReceivalTimeField;
        
        private CalendarEventReceiptErrorCodeType eventErrorCodeField;
        
        private string eventMessageField;
        
        private string originSystemIdentifierField;
        
        private bool conflictNotificationSentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.Guid PlannerResourceIdentifier {
            get {
                return this.plannerResourceIdentifierField;
            }
            set {
                this.plannerResourceIdentifierField = value;
                this.RaisePropertyChanged("PlannerResourceIdentifier");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PlannerResourceIdentifierSpecified {
            get {
                return this.plannerResourceIdentifierFieldSpecified;
            }
            set {
                this.plannerResourceIdentifierFieldSpecified = value;
                this.RaisePropertyChanged("PlannerResourceIdentifierSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.Guid CalendarEventIdentifier {
            get {
                return this.calendarEventIdentifierField;
            }
            set {
                this.calendarEventIdentifierField = value;
                this.RaisePropertyChanged("CalendarEventIdentifier");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.DateTime EventReceivalTime {
            get {
                return this.eventReceivalTimeField;
            }
            set {
                this.eventReceivalTimeField = value;
                this.RaisePropertyChanged("EventReceivalTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public CalendarEventReceiptErrorCodeType EventErrorCode {
            get {
                return this.eventErrorCodeField;
            }
            set {
                this.eventErrorCodeField = value;
                this.RaisePropertyChanged("EventErrorCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string EventMessage {
            get {
                return this.eventMessageField;
            }
            set {
                this.eventMessageField = value;
                this.RaisePropertyChanged("EventMessage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string OriginSystemIdentifier {
            get {
                return this.originSystemIdentifierField;
            }
            set {
                this.originSystemIdentifierField = value;
                this.RaisePropertyChanged("OriginSystemIdentifier");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public bool ConflictNotificationSent {
            get {
                return this.conflictNotificationSentField;
            }
            set {
                this.conflictNotificationSentField = value;
                this.RaisePropertyChanged("ConflictNotificationSent");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.bm.dk/PlannerExternalCalendarService/2015/03/27/")]
    public partial class CreateEventsResponseType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private CalendarEventReceiptType[] calendarEventReceiptField;
        
        private System.Guid serviceRequestLogReferenceIdentifierField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CalendarEventReceipt", Order=0)]
        public CalendarEventReceiptType[] CalendarEventReceipt {
            get {
                return this.calendarEventReceiptField;
            }
            set {
                this.calendarEventReceiptField = value;
                this.RaisePropertyChanged("CalendarEventReceipt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.Guid ServiceRequestLogReferenceIdentifier {
            get {
                return this.serviceRequestLogReferenceIdentifierField;
            }
            set {
                this.serviceRequestLogReferenceIdentifierField = value;
                this.RaisePropertyChanged("ServiceRequestLogReferenceIdentifier");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.bm.dk/PlannerExternalCalendarService/2015/03/27/")]
    public partial class CalendarEventType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime calendarEventStartTimeField;
        
        private System.DateTime calendarEventEndTimeField;
        
        private string originSystemIdentifierField;
        
        private string originEmailAddressField;
        
        private System.Guid plannerResourceIdentifierField;
        
        private bool plannerResourceIdentifierFieldSpecified;
        
        private System.Guid calendarEventIdentifierField;
        
        private bool calendarEventIdentifierFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.DateTime CalendarEventStartTime {
            get {
                return this.calendarEventStartTimeField;
            }
            set {
                this.calendarEventStartTimeField = value;
                this.RaisePropertyChanged("CalendarEventStartTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.DateTime CalendarEventEndTime {
            get {
                return this.calendarEventEndTimeField;
            }
            set {
                this.calendarEventEndTimeField = value;
                this.RaisePropertyChanged("CalendarEventEndTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string OriginSystemIdentifier {
            get {
                return this.originSystemIdentifierField;
            }
            set {
                this.originSystemIdentifierField = value;
                this.RaisePropertyChanged("OriginSystemIdentifier");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string OriginEmailAddress {
            get {
                return this.originEmailAddressField;
            }
            set {
                this.originEmailAddressField = value;
                this.RaisePropertyChanged("OriginEmailAddress");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public System.Guid PlannerResourceIdentifier {
            get {
                return this.plannerResourceIdentifierField;
            }
            set {
                this.plannerResourceIdentifierField = value;
                this.RaisePropertyChanged("PlannerResourceIdentifier");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PlannerResourceIdentifierSpecified {
            get {
                return this.plannerResourceIdentifierFieldSpecified;
            }
            set {
                this.plannerResourceIdentifierFieldSpecified = value;
                this.RaisePropertyChanged("PlannerResourceIdentifierSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public System.Guid CalendarEventIdentifier {
            get {
                return this.calendarEventIdentifierField;
            }
            set {
                this.calendarEventIdentifierField = value;
                this.RaisePropertyChanged("CalendarEventIdentifier");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CalendarEventIdentifierSpecified {
            get {
                return this.calendarEventIdentifierFieldSpecified;
            }
            set {
                this.calendarEventIdentifierFieldSpecified = value;
                this.RaisePropertyChanged("CalendarEventIdentifierSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://service.bm.dk/pjaktass/1/PlannerExternalCalendarService", ConfigurationName="DfdgService.PlannerExternalCalendarService")]
    public interface PlannerExternalCalendarService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.bm.dk/pjaktass/1/PlannerExternalCalendarService#CreateEvents", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(PlannerCalendarClient.ServiceDfdg.DfdgService.FaultDetails), Action="http://service.bm.dk/pjaktass/1/PlannerExternalCalendarService#CreateEvents", Name="FaultDetails", Namespace="http://service.bm.dk/xml/schemas/2011/01/12/")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CodeListItemIdentifierType))]
        PlannerCalendarClient.ServiceDfdg.DfdgService.CreateEventsResponse CreateEvents(PlannerCalendarClient.ServiceDfdg.DfdgService.CreateEventsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.bm.dk/pjaktass/1/PlannerExternalCalendarService#UpdateEvents", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(PlannerCalendarClient.ServiceDfdg.DfdgService.FaultDetails), Action="http://service.bm.dk/pjaktass/1/PlannerExternalCalendarService#UpdateEvents", Name="FaultDetails", Namespace="http://service.bm.dk/xml/schemas/2011/01/12/")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CodeListItemIdentifierType))]
        PlannerCalendarClient.ServiceDfdg.DfdgService.UpdateEventsResponse UpdateEvents(PlannerCalendarClient.ServiceDfdg.DfdgService.UpdateEventsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.bm.dk/pjaktass/1/PlannerExternalCalendarService#DeleteEvents", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(PlannerCalendarClient.ServiceDfdg.DfdgService.FaultDetails), Action="http://service.bm.dk/pjaktass/1/PlannerExternalCalendarService#DeleteEvents", Name="FaultDetails", Namespace="http://service.bm.dk/xml/schemas/2011/01/12/")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CodeListItemIdentifierType))]
        PlannerCalendarClient.ServiceDfdg.DfdgService.DeleteEventsResponse DeleteEvents(PlannerCalendarClient.ServiceDfdg.DfdgService.DeleteEventsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.bm.dk/pjaktass/1/PlannerExternalCalendarService#GetEvents", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(PlannerCalendarClient.ServiceDfdg.DfdgService.FaultDetails), Action="http://service.bm.dk/pjaktass/1/PlannerExternalCalendarService#GetEvents", Name="FaultDetails", Namespace="http://service.bm.dk/xml/schemas/2011/01/12/")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CodeListItemIdentifierType))]
        PlannerCalendarClient.ServiceDfdg.DfdgService.GetEventsResponse GetEvents(PlannerCalendarClient.ServiceDfdg.DfdgService.GetEventsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.bm.dk/pjaktass/1/PlannerExternalCalendarService#GetResources", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(PlannerCalendarClient.ServiceDfdg.DfdgService.FaultDetails), Action="http://service.bm.dk/pjaktass/1/PlannerExternalCalendarService#GetResources", Name="FaultDetails", Namespace="http://service.bm.dk/xml/schemas/2011/01/12/")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CodeListItemIdentifierType))]
        PlannerCalendarClient.ServiceDfdg.DfdgService.GetResourcesResponse GetResources(PlannerCalendarClient.ServiceDfdg.DfdgService.GetResourcesRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.bm.dk/RequestUserMetadata/2015/01/21/")]
    public partial class RequestUserMetadataType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private RequestUserStructureType requestUserStructureField;
        
        private RequestOrganisationStructureType requestOrganisationStructureField;
        
        private System.DateTime registrationDateTimeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://service.bm.dk/pjaktass/2015/01/21/RequestUserStructure/", Order=0)]
        public RequestUserStructureType RequestUserStructure {
            get {
                return this.requestUserStructureField;
            }
            set {
                this.requestUserStructureField = value;
                this.RaisePropertyChanged("RequestUserStructure");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://service.bm.dk/pjaktass/2015/01/21/RequestOrganisationStructure/", Order=1)]
        public RequestOrganisationStructureType RequestOrganisationStructure {
            get {
                return this.requestOrganisationStructureField;
            }
            set {
                this.requestOrganisationStructureField = value;
                this.RaisePropertyChanged("RequestOrganisationStructure");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.DateTime RegistrationDateTime {
            get {
                return this.registrationDateTimeField;
            }
            set {
                this.registrationDateTimeField = value;
                this.RaisePropertyChanged("RegistrationDateTime");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.bm.dk/pjaktass/2015/01/21/RequestUserStructure/")]
    public partial class RequestUserStructureType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string userFullNameField;
        
        private RequestUserTypeIdentifierType requestUserTypeIdentifierField;
        
        private string userIdentifierField;
        
        private string userEmailField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string UserFullName {
            get {
                return this.userFullNameField;
            }
            set {
                this.userFullNameField = value;
                this.RaisePropertyChanged("UserFullName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://service.bm.dk/pjaktass/2015/01/21/RequestUserTypeIdentifierCodeList/", Order=1)]
        public RequestUserTypeIdentifierType RequestUserTypeIdentifier {
            get {
                return this.requestUserTypeIdentifierField;
            }
            set {
                this.requestUserTypeIdentifierField = value;
                this.RaisePropertyChanged("RequestUserTypeIdentifier");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string UserIdentifier {
            get {
                return this.userIdentifierField;
            }
            set {
                this.userIdentifierField = value;
                this.RaisePropertyChanged("UserIdentifier");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string UserEmail {
            get {
                return this.userEmailField;
            }
            set {
                this.userEmailField = value;
                this.RaisePropertyChanged("UserEmail");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.bm.dk/pjaktass/2015/01/21/RequestOrganisationStructure/")]
    public partial class RequestOrganisationStructureType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private OrganisationTypeIdentifierType organisationTypeIdentifierField;
        
        private string organisationCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public OrganisationTypeIdentifierType OrganisationTypeIdentifier {
            get {
                return this.organisationTypeIdentifierField;
            }
            set {
                this.organisationTypeIdentifierField = value;
                this.RaisePropertyChanged("OrganisationTypeIdentifier");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string OrganisationCode {
            get {
                return this.organisationCodeField;
            }
            set {
                this.organisationCodeField = value;
                this.RaisePropertyChanged("OrganisationCode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rep.oio.dk/ams.dk/xml/schemas/2005/09/01/")]
    public partial class ActiveOrganisationHeaderType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int organisationTypeIdentifierField;
        
        private string organisationCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int OrganisationTypeIdentifier {
            get {
                return this.organisationTypeIdentifierField;
            }
            set {
                this.organisationTypeIdentifierField = value;
                this.RaisePropertyChanged("OrganisationTypeIdentifier");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string OrganisationCode {
            get {
                return this.organisationCodeField;
            }
            set {
                this.organisationCodeField = value;
                this.RaisePropertyChanged("OrganisationCode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateEventsRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://service.bm.dk/RequestUserMetadata/2015/01/21/")]
        public PlannerCalendarClient.ServiceDfdg.DfdgService.RequestUserMetadataType RequestUserMetadataHeader;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://rep.oio.dk/ams.dk/xml/schemas/2005/09/01/")]
        public PlannerCalendarClient.ServiceDfdg.DfdgService.ActiveOrganisationHeaderType ActiveOrganisationHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateEventsRequest", Namespace="http://service.bm.dk/PlannerExternalCalendarService/2015/03/27/", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("CalendarEvent", IsNullable=false)]
        public PlannerCalendarClient.ServiceDfdg.DfdgService.CalendarEventType[] CreateEventsRequest1;
        
        public CreateEventsRequest() {
        }
        
        public CreateEventsRequest(PlannerCalendarClient.ServiceDfdg.DfdgService.RequestUserMetadataType RequestUserMetadataHeader, PlannerCalendarClient.ServiceDfdg.DfdgService.ActiveOrganisationHeaderType ActiveOrganisationHeader, PlannerCalendarClient.ServiceDfdg.DfdgService.CalendarEventType[] CreateEventsRequest1) {
            this.RequestUserMetadataHeader = RequestUserMetadataHeader;
            this.ActiveOrganisationHeader = ActiveOrganisationHeader;
            this.CreateEventsRequest1 = CreateEventsRequest1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateEventsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateEventsResponse", Namespace="http://service.bm.dk/PlannerExternalCalendarService/2015/03/27/", Order=0)]
        public PlannerCalendarClient.ServiceDfdg.DfdgService.CreateEventsResponseType CreateEventsResponse1;
        
        public CreateEventsResponse() {
        }
        
        public CreateEventsResponse(PlannerCalendarClient.ServiceDfdg.DfdgService.CreateEventsResponseType CreateEventsResponse1) {
            this.CreateEventsResponse1 = CreateEventsResponse1;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.bm.dk/PlannerExternalCalendarService/2015/03/27/")]
    public partial class UpdateEventsResponseType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private CalendarEventReceiptType[] calendarEventReceiptField;
        
        private System.Guid serviceRequestLogReferenceIdentifierField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CalendarEventReceipt", Order=0)]
        public CalendarEventReceiptType[] CalendarEventReceipt {
            get {
                return this.calendarEventReceiptField;
            }
            set {
                this.calendarEventReceiptField = value;
                this.RaisePropertyChanged("CalendarEventReceipt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.Guid ServiceRequestLogReferenceIdentifier {
            get {
                return this.serviceRequestLogReferenceIdentifierField;
            }
            set {
                this.serviceRequestLogReferenceIdentifierField = value;
                this.RaisePropertyChanged("ServiceRequestLogReferenceIdentifier");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateEventsRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://service.bm.dk/RequestUserMetadata/2015/01/21/")]
        public PlannerCalendarClient.ServiceDfdg.DfdgService.RequestUserMetadataType RequestUserMetadataHeader;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://rep.oio.dk/ams.dk/xml/schemas/2005/09/01/")]
        public PlannerCalendarClient.ServiceDfdg.DfdgService.ActiveOrganisationHeaderType ActiveOrganisationHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateEventsRequest", Namespace="http://service.bm.dk/PlannerExternalCalendarService/2015/03/27/", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("CalendarEvent", IsNullable=false)]
        public PlannerCalendarClient.ServiceDfdg.DfdgService.CalendarEventType[] UpdateEventsRequest1;
        
        public UpdateEventsRequest() {
        }
        
        public UpdateEventsRequest(PlannerCalendarClient.ServiceDfdg.DfdgService.RequestUserMetadataType RequestUserMetadataHeader, PlannerCalendarClient.ServiceDfdg.DfdgService.ActiveOrganisationHeaderType ActiveOrganisationHeader, PlannerCalendarClient.ServiceDfdg.DfdgService.CalendarEventType[] UpdateEventsRequest1) {
            this.RequestUserMetadataHeader = RequestUserMetadataHeader;
            this.ActiveOrganisationHeader = ActiveOrganisationHeader;
            this.UpdateEventsRequest1 = UpdateEventsRequest1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateEventsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateEventsResponse", Namespace="http://service.bm.dk/PlannerExternalCalendarService/2015/03/27/", Order=0)]
        public PlannerCalendarClient.ServiceDfdg.DfdgService.UpdateEventsResponseType UpdateEventsResponse1;
        
        public UpdateEventsResponse() {
        }
        
        public UpdateEventsResponse(PlannerCalendarClient.ServiceDfdg.DfdgService.UpdateEventsResponseType UpdateEventsResponse1) {
            this.UpdateEventsResponse1 = UpdateEventsResponse1;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.bm.dk/PlannerExternalCalendarService/2015/03/27/")]
    public partial class DeleteEventsResponseType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private CalendarEventReceiptType[] calendarEventReceiptField;
        
        private System.Guid serviceRequestLogReferenceIdentifierField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CalendarEventReceipt", Order=0)]
        public CalendarEventReceiptType[] CalendarEventReceipt {
            get {
                return this.calendarEventReceiptField;
            }
            set {
                this.calendarEventReceiptField = value;
                this.RaisePropertyChanged("CalendarEventReceipt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.Guid ServiceRequestLogReferenceIdentifier {
            get {
                return this.serviceRequestLogReferenceIdentifierField;
            }
            set {
                this.serviceRequestLogReferenceIdentifierField = value;
                this.RaisePropertyChanged("ServiceRequestLogReferenceIdentifier");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteEventsRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://service.bm.dk/RequestUserMetadata/2015/01/21/")]
        public PlannerCalendarClient.ServiceDfdg.DfdgService.RequestUserMetadataType RequestUserMetadataHeader;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://rep.oio.dk/ams.dk/xml/schemas/2005/09/01/")]
        public PlannerCalendarClient.ServiceDfdg.DfdgService.ActiveOrganisationHeaderType ActiveOrganisationHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteEventsRequest", Namespace="http://service.bm.dk/PlannerExternalCalendarService/2015/03/27/", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("CalendarEvent", IsNullable=false)]
        public PlannerCalendarClient.ServiceDfdg.DfdgService.CalendarEventType[] DeleteEventsRequest1;
        
        public DeleteEventsRequest() {
        }
        
        public DeleteEventsRequest(PlannerCalendarClient.ServiceDfdg.DfdgService.RequestUserMetadataType RequestUserMetadataHeader, PlannerCalendarClient.ServiceDfdg.DfdgService.ActiveOrganisationHeaderType ActiveOrganisationHeader, PlannerCalendarClient.ServiceDfdg.DfdgService.CalendarEventType[] DeleteEventsRequest1) {
            this.RequestUserMetadataHeader = RequestUserMetadataHeader;
            this.ActiveOrganisationHeader = ActiveOrganisationHeader;
            this.DeleteEventsRequest1 = DeleteEventsRequest1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteEventsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteEventsResponse", Namespace="http://service.bm.dk/PlannerExternalCalendarService/2015/03/27/", Order=0)]
        public PlannerCalendarClient.ServiceDfdg.DfdgService.DeleteEventsResponseType DeleteEventsResponse1;
        
        public DeleteEventsResponse() {
        }
        
        public DeleteEventsResponse(PlannerCalendarClient.ServiceDfdg.DfdgService.DeleteEventsResponseType DeleteEventsResponse1) {
            this.DeleteEventsResponse1 = DeleteEventsResponse1;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.bm.dk/PlannerExternalCalendarService/2015/03/27/")]
    public partial class GetEventsRequestType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private CalendarResourceType[] calendarResourceField;
        
        private System.DateTime eventStartFromDateTimeField;
        
        private bool eventStartFromDateTimeFieldSpecified;
        
        private System.DateTime eventStartToDateTimeField;
        
        private bool eventStartToDateTimeFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CalendarResource", Order=0)]
        public CalendarResourceType[] CalendarResource {
            get {
                return this.calendarResourceField;
            }
            set {
                this.calendarResourceField = value;
                this.RaisePropertyChanged("CalendarResource");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.DateTime EventStartFromDateTime {
            get {
                return this.eventStartFromDateTimeField;
            }
            set {
                this.eventStartFromDateTimeField = value;
                this.RaisePropertyChanged("EventStartFromDateTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool EventStartFromDateTimeSpecified {
            get {
                return this.eventStartFromDateTimeFieldSpecified;
            }
            set {
                this.eventStartFromDateTimeFieldSpecified = value;
                this.RaisePropertyChanged("EventStartFromDateTimeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.DateTime EventStartToDateTime {
            get {
                return this.eventStartToDateTimeField;
            }
            set {
                this.eventStartToDateTimeField = value;
                this.RaisePropertyChanged("EventStartToDateTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool EventStartToDateTimeSpecified {
            get {
                return this.eventStartToDateTimeFieldSpecified;
            }
            set {
                this.eventStartToDateTimeFieldSpecified = value;
                this.RaisePropertyChanged("EventStartToDateTimeSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.bm.dk/PlannerExternalCalendarService/2015/03/27/")]
    public partial class CalendarResourceType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string calendarResourceNameField;
        
        private string rIDField;
        
        private string calendarResourceEmailAddressField;
        
        private System.Guid plannerResourceIdentifierField;
        
        private bool plannerResourceIdentifierFieldSpecified;
        
        private WorkingHoursType[] workingHoursField;
        
        private string calendarResourceDescriptionField;
        
        private bool isCaseWorkerField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string CalendarResourceName {
            get {
                return this.calendarResourceNameField;
            }
            set {
                this.calendarResourceNameField = value;
                this.RaisePropertyChanged("CalendarResourceName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string RID {
            get {
                return this.rIDField;
            }
            set {
                this.rIDField = value;
                this.RaisePropertyChanged("RID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string CalendarResourceEmailAddress {
            get {
                return this.calendarResourceEmailAddressField;
            }
            set {
                this.calendarResourceEmailAddressField = value;
                this.RaisePropertyChanged("CalendarResourceEmailAddress");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public System.Guid PlannerResourceIdentifier {
            get {
                return this.plannerResourceIdentifierField;
            }
            set {
                this.plannerResourceIdentifierField = value;
                this.RaisePropertyChanged("PlannerResourceIdentifier");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PlannerResourceIdentifierSpecified {
            get {
                return this.plannerResourceIdentifierFieldSpecified;
            }
            set {
                this.plannerResourceIdentifierFieldSpecified = value;
                this.RaisePropertyChanged("PlannerResourceIdentifierSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("WorkingHours", Order=4)]
        public WorkingHoursType[] WorkingHours {
            get {
                return this.workingHoursField;
            }
            set {
                this.workingHoursField = value;
                this.RaisePropertyChanged("WorkingHours");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string CalendarResourceDescription {
            get {
                return this.calendarResourceDescriptionField;
            }
            set {
                this.calendarResourceDescriptionField = value;
                this.RaisePropertyChanged("CalendarResourceDescription");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public bool IsCaseWorker {
            get {
                return this.isCaseWorkerField;
            }
            set {
                this.isCaseWorkerField = value;
                this.RaisePropertyChanged("IsCaseWorker");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.bm.dk/PlannerExternalCalendarService/2015/03/27/")]
    public partial class WorkingHoursType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int workingHoursWeekdayField;
        
        private System.DateTime workingHoursStartTimeField;
        
        private System.DateTime workingHoursEndTimeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int WorkingHoursWeekday {
            get {
                return this.workingHoursWeekdayField;
            }
            set {
                this.workingHoursWeekdayField = value;
                this.RaisePropertyChanged("WorkingHoursWeekday");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.DateTime WorkingHoursStartTime {
            get {
                return this.workingHoursStartTimeField;
            }
            set {
                this.workingHoursStartTimeField = value;
                this.RaisePropertyChanged("WorkingHoursStartTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.DateTime WorkingHoursEndTime {
            get {
                return this.workingHoursEndTimeField;
            }
            set {
                this.workingHoursEndTimeField = value;
                this.RaisePropertyChanged("WorkingHoursEndTime");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.bm.dk/PlannerExternalCalendarService/2015/03/27/")]
    public partial class GetEventsResponseType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private CalendarEventType[] calendarEventField;
        
        private System.Guid serviceRequestLogReferenceIdentifierField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CalendarEvent", Order=0)]
        public CalendarEventType[] CalendarEvent {
            get {
                return this.calendarEventField;
            }
            set {
                this.calendarEventField = value;
                this.RaisePropertyChanged("CalendarEvent");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.Guid ServiceRequestLogReferenceIdentifier {
            get {
                return this.serviceRequestLogReferenceIdentifierField;
            }
            set {
                this.serviceRequestLogReferenceIdentifierField = value;
                this.RaisePropertyChanged("ServiceRequestLogReferenceIdentifier");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetEventsRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://service.bm.dk/RequestUserMetadata/2015/01/21/")]
        public PlannerCalendarClient.ServiceDfdg.DfdgService.RequestUserMetadataType RequestUserMetadataHeader;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://rep.oio.dk/ams.dk/xml/schemas/2005/09/01/")]
        public PlannerCalendarClient.ServiceDfdg.DfdgService.ActiveOrganisationHeaderType ActiveOrganisationHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetEventsRequest", Namespace="http://service.bm.dk/PlannerExternalCalendarService/2015/03/27/", Order=0)]
        public PlannerCalendarClient.ServiceDfdg.DfdgService.GetEventsRequestType GetEventsRequest1;
        
        public GetEventsRequest() {
        }
        
        public GetEventsRequest(PlannerCalendarClient.ServiceDfdg.DfdgService.RequestUserMetadataType RequestUserMetadataHeader, PlannerCalendarClient.ServiceDfdg.DfdgService.ActiveOrganisationHeaderType ActiveOrganisationHeader, PlannerCalendarClient.ServiceDfdg.DfdgService.GetEventsRequestType GetEventsRequest1) {
            this.RequestUserMetadataHeader = RequestUserMetadataHeader;
            this.ActiveOrganisationHeader = ActiveOrganisationHeader;
            this.GetEventsRequest1 = GetEventsRequest1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetEventsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetEventsResponse", Namespace="http://service.bm.dk/PlannerExternalCalendarService/2015/03/27/", Order=0)]
        public PlannerCalendarClient.ServiceDfdg.DfdgService.GetEventsResponseType GetEventsResponse1;
        
        public GetEventsResponse() {
        }
        
        public GetEventsResponse(PlannerCalendarClient.ServiceDfdg.DfdgService.GetEventsResponseType GetEventsResponse1) {
            this.GetEventsResponse1 = GetEventsResponse1;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.bm.dk/PlannerExternalCalendarService/2015/03/27/")]
    public partial class GetResourcesResponseType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private CalendarResourceType[] calendarResourceField;
        
        private System.Guid serviceRequestLogReferenceIdentifierField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CalendarResource", Order=0)]
        public CalendarResourceType[] CalendarResource {
            get {
                return this.calendarResourceField;
            }
            set {
                this.calendarResourceField = value;
                this.RaisePropertyChanged("CalendarResource");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.Guid ServiceRequestLogReferenceIdentifier {
            get {
                return this.serviceRequestLogReferenceIdentifierField;
            }
            set {
                this.serviceRequestLogReferenceIdentifierField = value;
                this.RaisePropertyChanged("ServiceRequestLogReferenceIdentifier");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetResourcesRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://service.bm.dk/RequestUserMetadata/2015/01/21/")]
        public PlannerCalendarClient.ServiceDfdg.DfdgService.RequestUserMetadataType RequestUserMetadataHeader;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://rep.oio.dk/ams.dk/xml/schemas/2005/09/01/")]
        public PlannerCalendarClient.ServiceDfdg.DfdgService.ActiveOrganisationHeaderType ActiveOrganisationHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetResourcesRequest", Namespace="http://service.bm.dk/PlannerExternalCalendarService/2015/03/27/", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("EmailAddressIdentifier", IsNullable=false)]
        public string[] GetResourcesRequest1;
        
        public GetResourcesRequest() {
        }
        
        public GetResourcesRequest(PlannerCalendarClient.ServiceDfdg.DfdgService.RequestUserMetadataType RequestUserMetadataHeader, PlannerCalendarClient.ServiceDfdg.DfdgService.ActiveOrganisationHeaderType ActiveOrganisationHeader, string[] GetResourcesRequest1) {
            this.RequestUserMetadataHeader = RequestUserMetadataHeader;
            this.ActiveOrganisationHeader = ActiveOrganisationHeader;
            this.GetResourcesRequest1 = GetResourcesRequest1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetResourcesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetResourcesResponse", Namespace="http://service.bm.dk/PlannerExternalCalendarService/2015/03/27/", Order=0)]
        public PlannerCalendarClient.ServiceDfdg.DfdgService.GetResourcesResponseType GetResourcesResponse1;
        
        public GetResourcesResponse() {
        }
        
        public GetResourcesResponse(PlannerCalendarClient.ServiceDfdg.DfdgService.GetResourcesResponseType GetResourcesResponse1) {
            this.GetResourcesResponse1 = GetResourcesResponse1;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PlannerExternalCalendarServiceChannel : PlannerCalendarClient.ServiceDfdg.DfdgService.PlannerExternalCalendarService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PlannerExternalCalendarServiceClient : System.ServiceModel.ClientBase<PlannerCalendarClient.ServiceDfdg.DfdgService.PlannerExternalCalendarService>, PlannerCalendarClient.ServiceDfdg.DfdgService.PlannerExternalCalendarService {
        
        public PlannerExternalCalendarServiceClient() {
        }
        
        public PlannerExternalCalendarServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PlannerExternalCalendarServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PlannerExternalCalendarServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PlannerExternalCalendarServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public PlannerCalendarClient.ServiceDfdg.DfdgService.CreateEventsResponse CreateEvents(PlannerCalendarClient.ServiceDfdg.DfdgService.CreateEventsRequest request) {
            return base.Channel.CreateEvents(request);
        }
        
        public PlannerCalendarClient.ServiceDfdg.DfdgService.UpdateEventsResponse UpdateEvents(PlannerCalendarClient.ServiceDfdg.DfdgService.UpdateEventsRequest request) {
            return base.Channel.UpdateEvents(request);
        }
        
        public PlannerCalendarClient.ServiceDfdg.DfdgService.DeleteEventsResponse DeleteEvents(PlannerCalendarClient.ServiceDfdg.DfdgService.DeleteEventsRequest request) {
            return base.Channel.DeleteEvents(request);
        }
        
        public PlannerCalendarClient.ServiceDfdg.DfdgService.GetEventsResponse GetEvents(PlannerCalendarClient.ServiceDfdg.DfdgService.GetEventsRequest request) {
            return base.Channel.GetEvents(request);
        }
        
        public PlannerCalendarClient.ServiceDfdg.DfdgService.GetResourcesResponse GetResources(PlannerCalendarClient.ServiceDfdg.DfdgService.GetResourcesRequest request) {
            return base.Channel.GetResources(request);
        }
    }
}
