//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlannerCalendarClient.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CalendarEvent
    {
        public CalendarEvent()
        {
            this.SyncLogs = new HashSet<SyncLog>();
        }
    
        public long Id { get; set; }
        public string MailAddress { get; set; }
        public string CalId { get; set; }
        public Nullable<System.Guid> PlannerCalendarEventId { get; set; }
        public Nullable<System.Guid> PlannerResourceId { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual ICollection<SyncLog> SyncLogs { get; set; }
    }
}
