//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlannerCalendarClient.DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ECSClientExchangeDbEntities : DbContext
    {
        public ECSClientExchangeDbEntities()
            : base("name=ECSClientExchangeDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CalendarEvent> CalendarEvents { get; set; }
        public virtual DbSet<Notification> Notifications { get; set; }
        public virtual DbSet<PlannerResource> PlannerResources { get; set; }
        public virtual DbSet<ServiceCallReferenceLog> ServiceCallReferenceLogs { get; set; }
        public virtual DbSet<SyncLog> SyncLogs { get; set; }
        public virtual DbSet<ServiceUserCredential> ServiceUserCredentials { get; set; }
        public virtual DbSet<Subscription> Subscriptions { get; set; }
        public virtual DbSet<PlannerResourceWhitelist> PlannerResourceWhitelists { get; set; }
        public virtual DbSet<PlannerResourceBlacklist> PlannerResourceBlacklists { get; set; }
        public virtual DbSet<NotificationLog> NotificationLogs { get; set; }
    }
}
