//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlannerCalendarClient.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotificationLog
    {
        public long Id { get; set; }
        public string EwsId { get; set; }
        public System.DateTime EwsTimestamp { get; set; }
        public Nullable<System.DateTime> ReceiveTime { get; set; }
        public Nullable<System.DateTime> ProcessedTime { get; set; }
        public string ResponseText { get; set; }
    }
}
