//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlannerCalendarClient.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlannerResource
    {
        public long Id { get; set; }
        public string MailAddress { get; set; }
        public Nullable<System.Guid> PlannerResourceId { get; set; }
        public string GroupAffinity { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public string ErrorCode { get; set; }
        public string ErrorDescription { get; set; }
        public Nullable<System.DateTime> ErrorDate { get; set; }
        public Nullable<System.DateTime> LastFullSync { get; set; }
    
        public virtual Subscription Subscription { get; set; }
    }
}
