//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlannerCalendarClient.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceUserCredential
    {
        public ServiceUserCredential()
        {
            this.Subscriptions = new HashSet<Subscription>();
        }
    
        public long Id { get; set; }
        public string UserId { get; set; }
        public string Password { get; set; }
    
        public virtual ICollection<Subscription> Subscriptions { get; set; }
    }
}
