//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlannerCalendarClient.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subscription
    {
        public Subscription()
        {
            this.PlannerResources = new HashSet<PlannerResource>();
        }
    
        public long Id { get; set; }
        public string GroupAffinity { get; set; }
        public Nullable<long> ServiceUserCredentialId { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual ServiceUserCredential ServiceUserCredential { get; set; }
        public virtual ICollection<PlannerResource> PlannerResources { get; set; }
    }
}
