//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlannerCalendarClient.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class SyncLog
    {
        public long Id { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public long CalendarEventId { get; set; }
        public System.DateTime CalendarStart { get; set; }
        public System.DateTime CalendarEnd { get; set; }
        public string Operation { get; set; }
        public Nullable<System.DateTime> SyncDate { get; set; }
        public Nullable<long> ServiceCallReferenceLogId { get; set; }
        public Nullable<bool> PlannerSyncSuccess { get; set; }
        public string PlannerSyncResponse { get; set; }
        public Nullable<int> PlannerEventErrorCode { get; set; }
        public Nullable<long> NotificationLogId { get; set; }
    
        public virtual CalendarEvent CalendarEvent { get; set; }
        public virtual ServiceCallReferenceLog ServiceCallReferenceLog { get; set; }
    }
}
